"use client";
import "./styles/global.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { createContext, useState, useContext } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const queryClient = new QueryClient();
const DataContext = createContext({});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  const [user, setUser] = useState(null);
  return (
    <QueryClientProvider client={queryClient}>
      <DataContext.Provider value={{ user, setUser }}>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </DataContext.Provider>
    </QueryClientProvider>
  );
}

export const useData = () => {
  return useContext(DataContext);
};
